### ISSUE TITLE
Particlex 主题使用说明 | Argvchs の小窝

### ISSUE THREAD

**Issue by argvchs** [argvchs/gitalk-comments#6]
https://argvchs.netlify.app/2022/05/10/hexo-theme-particlex/

**Comment by ytt521** [comment]
真不戳

**Comment by whl-1998** [comment]
老哥鼠标动态雨点这个特效，配置里有么

**Comment by daisukiMarisada** [comment]
好棒

**Comment by xixi-cmd** [comment]
作者大大，我昨天研究了一个晚上还是没搞明白那个图标的引入规则，希望优化~

**Comment by KiteMoon** [comment]
似乎有个小问题，我写入文章后，在首页，所有的文章都以完整的形式展示(而不是使用缩略信息的方式）这样会导致整个页面极度炸裂 速度很慢很慢,具体如下图
![](https://pic.sikadi.top/internationBlog/2022/08/20220823000413.png)
原文档已经写入了简介等信息
![](https://pic.sikadi.top/internationBlog/2022/08/20220823000513.png)

**Comment by argvchs** [comment]
额，缩略信息的话在 markdown 文档中间加一个 `<!-- more -->` 就可以了
`<!-- more -->` 后面的都不会在主页展示

**Comment by KiteMoon** [comment]
> @argvchs
> 额，缩略信息的话在 markdown 文档中间加一个 `<!-- more -->` 就可以了
> `<!-- more -->` 后面的都不会在主页展示

哦哦，好吧，但是这样好怪，这个以后能优化为使用标头字段来实现么？就是最开始yaml中简介字段，来实现(因为很多时候首页内容可能是大概介绍下这篇文章讲什么，映射到正文会显得比较乱

**Comment by argvchs** [comment]
@KiteMoon 更新了，看一下 README 的首页文档缩略配置

**Comment by KiteMoon** [comment]
> @argvchs
> @KiteMoon 更新了，看一下 README 的首页文档缩略配置

好耶，非常感谢

**Comment by 12109uuu** [comment]
请问导航栏的文件写在哪，刚上手有点摸不着头

**Comment by argvchs** [comment]
`themes/particlex/_config.yml`

**Comment by 12109uuu** [comment]
> `themes/particlex/_config.yml`

不是这个，是md文件放哪emmm

**Comment by argvchs** [comment]
`source\_posts\<name>.md`

**Comment by 12109uuu** [comment]
> `source\_posts\<name>.md`

谢谢谢谢！

**Comment by 12109uuu** [comment]
等等，我换个问法，导航栏about.md放哪

**Comment by 12109uuu** [comment]
这个好像是放到博客栏那边了


> `source\_posts\<name>.md`

**Comment by argvchs** [comment]
![image](https://user-images.githubusercontent.com/64528288/186313355-c5879113-ac8f-4c95-b7bd-4d55b2cf1f92.png)

**Comment by Rainbownight** [comment]
> @whl-1998
> 老哥鼠标动态雨点这个特效，配置里有么

->[佬的Hexo教程III](https://argvchs.github.io/2022/04/17/hexo-blog-3/)

**Comment by argvchs** [comment]
中文字体我没改成可变字体，你看 css/notosanssc 和 css/test/notosanssc 的大小
-test （有一个减号）文件夹有真正的中文可变字体，全都在一个文件里，可是一次就要全部导入

其实 `description: 内容` 已经有内置设置 [excerpt](https://hexo.io/zh-cn/docs/front-matter) 了。。。

为什么不用数组？数组多行很直观啊

**Comment by KiteMoon** [comment]
> @argvchs
> 中文字体我没改成可变字体，你看 css/notosanssc 和 css/test/notosanssc 的大小
> -test （有一个减号）文件夹有真正的中文可变字体，全都在一个文件里，可是一次就要全部导入
> 
> 其实 `description: 内容` 已经有内置设置 [excerpt](https://hexo.io/zh-cn/docs/front-matter) 了。。。
> 
> 为什么不用数组？数组多行很直观啊

就感觉文件超多，rsync处理这种特别多得文件的时候会有卡顿（一个action跑到超时），目前是用删了的方法解决，看后面有没有什么办法能给他在配置文件关掉，不然之后导入就只能打一次包再发送上去了（同时HTML中一次性加载大量文件确实会影响速度）

至于为啥不用数组，其实是因为我看到大多数主题都是用了str，其次，如果要换行应该可以直接使用`\n`这样来操作吧，多行数组确实没怎么见过(现在撰写完文章后都是分两个版本，一个标准版本，一个主题特殊版）

PS：引用框作为预览内容的呈现好怪配，为什么不直接和more一样的展示方式呢（就感觉很突兀）？

现在我[站点](https://blog.kitemoon.cn/)就是删除了所有可变字体，30+报错也还能勉强用？

**Comment by argvchs** [comment]
（？Github Action 改成命令行部署

其实。。。分片文件不需要的字符集就不会加载了（应该是？
我是从 Google Fonts 上打包下载的字体文件

为什么预览是这样的格式：不是？你发的图片里 Description 就是引用的格式啊。。。

内部链接：[。。](https://github.com/argvchs/hexo-theme-particlex/issues/6)

**Comment by argvchs** [comment]
更新了，文章预览改成单行字符串，支持 markdown

**Comment by U1oSun** [comment]
为什么language那里写chinese还是英文版阿

**Comment by KiteMoon** [comment]
> @argvchs
> Github Action 不要用 `hexo cl/hexo clear` 清除缓存，不然很慢（？改成命令行部署
> 
> 其实。。。分片文件不需要的字符集就不会加载了（应该是？
> 我是从 Google Fonts 上打包下载的字体文件
> 
> 为什么预览是这样的格式：不是？你发的图片里 Description 就是引用的格式啊。。。
> 
> 内部链接：[。。](https://github.com/argvchs/hexo-theme-particlex/issues/6)

没有用 hexo clean，直接上传的public文件夹，就是单纯慢在rsync，命令行部署没找到好的Action（主要是要把文件发送到远程服务器这个过程很慢），具体参考配置如下

```yaml
name: Hexo deploy

on: 
  push:
    branches:
      - main
jobs:
  install:
    name: initEnv
    runs-on: ubuntu-20.04
    steps:
    - name: install hexo
      uses: actions/setup-node@v3
      with:
        node-version: '16.14'
    - name: install hexo and them
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: | 
        mkdir ~/.ssh
        echo $DEPLOY_KEY>~/.ssh/id-rsa
        git clone https://${{ secrets.GIT_TOKEN }}@github.com/KiteMoon/<脱敏>.git
        cd <脱敏>
        npm install hexo-cli -g
        npm install ./
        git config --global user.name "kitemoon"
        git config --global user.email "xie@loli.fit"
        hexo generate
        pwd
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_ACCESS_TOKEN }}
        ARGS: "-rltgoDzvO"
        SOURCE: "<脱敏>/public/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}  
```

其他就没有什么问题啦（哈哈）。感谢大佬的更新（嘿嘿）
